# Generated by Django 5.0.1 on 2024-01-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dono',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rede_social',
            name='dono',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='dono',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
            preserve_default=False,
        ),
    ]
