# Generated by Django 5.1.6 on 2025-02-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_projeto_dono_rede_social_dono_skill_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_pc',
            field=models.ImageField(null=True, upload_to='usuario/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto_tablet',
            field=models.ImageField(null=True, upload_to='usuario/'),
        ),
    ]
