# Generated by Django 5.2 on 2025-05-07 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_foto_pc_usuario_foto_tablet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=15, unique=True)),
                ('foto', models.ImageField(null=True, upload_to='projetos/')),
                ('sobre', models.TextField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
