# Generated by Django 5.2 on 2025-05-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_diploma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='foto',
            field=models.ImageField(null=True, upload_to='diplomas/'),
        ),
    ]
